Extract podpourri-job and podpourri-job-local

diff --git a/bin/podpourri-schedule b/bin/podpourri-schedule
--- a/bin/podpourri-schedule
+++ b/bin/podpourri-schedule
@@ -1,64 +1,33 @@
 #!/bin/sh
 #
-# podpourri-schedule - Sets up schedule for automated container image rebuilds
+# podpourri-schedule - Sets up schedule for automated container image rebuilds.
 
 set -eu
 
 CONFIGFILE="${HOME}/.config/podpourri/podpourri.conf"
-AUTOBUILD_DAILY="$(/usr/bin/env git config --file "${CONFIGFILE}" autobuild.daily || echo)"
-AUTOBUILD_WEEKLY="$(/usr/bin/env git config --file "${CONFIGFILE}" autobuild.weekly || echo)"
-AUTOBUILD_URL_PREFIX="$(/usr/bin/env git config --file "${CONFIGFILE}" autobuild.prefix || echo)"
 AUTOBUILD_METHOD="$(/usr/bin/env git config --file "${CONFIGFILE}" autobuild.method || echo systemd-user)"
 
 # Print usage message and exit.
 usage() {
-    echo "${0}: systemctl [systemctl args...]"
+    echo "${0}: schedule repo-url"
     return 1
 }
 
 podpourri_schedule() {
     case "${AUTOBUILD_METHOD}" in
         *[!a-zA-Z0-9-_.]*)
-            echo "Podpourri: Autobuild method" >&2
+            echo "Podpourri: Invalid autobuild method" >&2
             return 1
             ;;
+
         *)
-            HOOK="podpourri-schedule-${AUTOBUILD_METHOD}"
+            /usr/bin/env "podpourri-schedule-${AUTOBUILD_METHOD}" "${@}"
             ;;
-    esac
-
-    BRANCH="$(/usr/bin/env git rev-parse --abbrev-ref HEAD)"
-    case "${BRANCH}" in
-        *[!a-zA-Z0-9-_.]*)
-            echo "Podpourri: Invalid ref, not scheduling build" >&2
-            ;;
-        *)
-            ORIGIN="$(/usr/bin/env git remote get-url origin)"
-            IMAGE_NAME="${ORIGIN%/}"
-            IMAGE_NAME="${IMAGE_NAME##*[:/]}"
-            IMAGE_NAME="${IMAGE_NAME%.git}"
-
-            AUTOBUILD_URL="${ORIGIN}"
-            if [ -n "${AUTOBUILD_URL_PREFIX}" ]; then
-                AUTOBUILD_URL="${AUTOBUILD_URL_PREFIX}${IMAGE_NAME}"
-            fi
-
-            for REF in ${AUTOBUILD_DAILY}; do
-                if [ "${REF}" = "${BRANCH}" ]; then
-                    /usr/bin/env "${HOOK}" daily "${AUTOBUILD_URL}" "${BRANCH}"
-                fi
-            done
-
-            for REF in ${AUTOBUILD_WEEKLY}; do
-                if [ "${REF}" = "${BRANCH}" ]; then
-                    /usr/bin/env "${HOOK}" weekly "${AUTOBUILD_URL}" "${BRANCH}"
-                fi
-            done
     esac
 }
 
-if [ "${1:-}" != "-h" ] && [ "${1:-}" != "--help" ]; then
-    podpourri_schedule
+if [ "${#}" -eq 2 ] && [ "${1:-}" != "-h" ] && [ "${1:-}" != "--help" ]; then
+    podpourri_schedule "${@}"
 else
     usage
 fi
diff --git a/lib/git-hooks/post-receive b/lib/git-hooks/post-receive
--- a/lib/git-hooks/post-receive
+++ b/lib/git-hooks/post-receive
@@ -1,34 +1,50 @@
 #!/bin/sh
 #
-# Loop through all refs in a post-receive hook and run podpourri-build.
+# Loop through all refs in a post-receive hook, submit podpourri-job to
+# initiate a build and schedule automated rebuilds.
 
 set -eu
 
 umask 0022
 
+CONFIGFILE="${HOME}/.config/podpourri/podpourri.conf"
+REPO_BASEDIR="$(/usr/bin/env git config --file "${CONFIGFILE}" repo.basedir)"
+REPO_BASEURL="$(/usr/bin/env git config --file "${CONFIGFILE}" repo.baseurl)"
+AUTOBUILD_SCHEDULES="$(/usr/bin/env git config --file "${CONFIGFILE}" autobuild.schedules || echo daily weekly)"
+
 while read -r _ _ REFNAME
 do
     # Remove refs/heads/ prefix (if matching).
     BRANCH=${REFNAME#refs/heads/}
+
     case "${BRANCH}" in
         *[!a-zA-Z0-9-_.]*)
             # Invalid ref name. This is either a tag and thus containing
-            # slashes (refs/tags/...) or it is a branch containing characters
-            # which are not suitable as image tags. Skipping build.
+            # slashes (refs/tags/...) or it is a branch containing
+            # characters which are not suitable as image tags. Skipping
+            # build.
+            echo "[WARN] Podpourri: Skipping build, invalid ref: ${BRANCH}" >&2
             ;;
+
         *)
-            PODPOURRI_REPO="${PWD}#${BRANCH}"
-            PODPOURRI_JOBTAG_PREFIX="build-push-"
+            REPO_URL="${PWD}#${BRANCH}"
+            if [ -n "$REPO_BASEDIR" ]; then
+                REPO_URL="${REPO_URL##${REPO_BASEDIR}}"
+            fi
+            if [ -n "$REPO_BASEURL" ]; then
+                REPO_URL="${REPO_URL_PREFIX}${REPO_URL}"
+            fi
 
-            /usr/bin/env \
-                git gau-exec "${PODPOURRI_REPO}" \
-                podpourri-tag-xargs "${PODPOURRI_JOBTAG_PREFIX}" -I"{PODPOURRI_JOBTAG}" \
-                git gau-at "{PODPOURRI_JOBTAG}" \
-                git gau-xargs -I"{WORKDIR}" \
-                podpourri-build "{WORKDIR}" "{PODPOURRI_JOBTAG}" podman
+            podpourri-job "build-push-" "${REPO_URL}"
 
-            /usr/bin/env \
-                git gau-exec "${PODPOURRI_REPO}" podpourri-schedule
+            for SCHEDULE in ${AUTOBUILD_SCHEDULES}; do
+                AUTOBUILD_REFS="$(/usr/bin/env git config --file "${CONFIGFILE}" autobuild."${SCHEDULE}" || echo)"
+                for REF in ${AUTOBUILD_REFS}; do
+                    if [ "${REF}" = "${BRANCH}" ]; then
+                        podpourri-schedule "${SCHEDULE}" "${REPO_URL}"
+                    fi
+                if
+            done
             ;;
     esac
 done
